name: Create phantom files

on:
  workflow_dispatch:
  schedule:
    - cron: "* */6 * * *"

jobs:
  compare-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.GHOST_UPLOAD_TOKEN }}
      run: | 
        python ./3rd/GhostESP.py
      
    - name: Set up Git
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        
    - name: Commit
      id: compare
      run: |
          git add .
          git commit -m "Update JSON files"
          git push
